ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - agentdb
  - agentic-flow
  - argon2
  - bcrypt
  - better-sqlite3
  - esbuild
  - hnswlib-node
  - onnxruntime-node
  - protobufjs
  - sharp
  - sqlite3
  - tldjs
  - unrs-resolver
