allowBuilds:
  '@parcel/watcher': set this to true or false
  '@sentry/cli': set this to true or false
  esbuild: set this to true or false
  netlify-cli: set this to true or false
  sharp: set this to true or false
  unix-dgram: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - '@google/genai'
  - '@parcel/watcher'
  - '@sentry/cli'
  - agentdb
  - agentic-flow
  - argon2
  - bcrypt
  - better-sqlite3
  - esbuild
  - hnswlib-node
  - netlify-cli
  - onnxruntime-node
  - protobufjs
  - sharp
  - sqlite3
  - tldjs
  - unix-dgram
  - unrs-resolver
